# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chat-client-20250106155647

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_95db38d8018c46f9bee660e134ec6ce3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_de512cc54fad4fb3ac850a8daf6cc145 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_95db38d8018c46f9bee660e134ec6ce3 }}/sse-chat-client:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chat-client-20250106155647'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6792b9a93f2e416b820b8bb6ca7fa504 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_95db38d8018c46f9bee660e134ec6ce3 }}/sse-chat-client:${{ github.sha }}'