name: Build and deploy container app to Azure Web App - chat-server-20250106153359

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_87d41426752942af95cf83ef1cff800f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b75f629c6144ae1accf9c6c9f640b1d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./Server
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_87d41426752942af95cf83ef1cff800f }}/sse-chat-server:${{ github.sha }}
        file: ./Server/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chat-server-20250106153359'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e046bf587031418eb66a471b32ad6f13 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_87d41426752942af95cf83ef1cff800f }}/sse-chat-server:${{ github.sha }}'
